name = "Mueller"
uuid = "dfba0342-83e6-42c7-a796-fcf383ab214c"
authors = ["Miles Lucas <mdlucas@hawaii.edu> and contributors"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
RecipesBase = "1.2"
StaticArrays = "1.2"
julia = "1.5"
